# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/03 training.transcription.generation.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/03 training.transcription.generation.ipynb 4
from pathlib import Path

from ...data.download import load_config, \
    get_latest_assembly_path, get_genomic_genbank_path
from .index import get_intron_locations
