# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/02 training.transcription.index.ipynb.

# %% auto 0
__all__ = ['random_state', 'get_intron_locations']

# %% ../../../nbs/02 training.transcription.index.ipynb 2
# import os
from pathlib import Path
import pandas as pd
from tqdm import tqdm
# from sklearn.model_selection import train_test_split
# import torch
# from torch import Tensor
# from torch.utils.data import Dataset
# from torchtext.vocab import vocab, Vocab
# from collections import Counter, OrderedDict
# from multiprocessing import Pool

tqdm.pandas()

from ...data.download import load_config, \
    get_latest_assembly_path, get_genomic_genbank_path

random_state = 42

# %% ../../../nbs/02 training.transcription.index.ipynb 7
def get_intron_locations(path: Path) -> pd.DataFrame:
    # Index files
    chromosome_parquet_files = list(path.glob("*.parquet"))
    frames = []
    for f in chromosome_parquet_files:
        f_frame = pd.read_parquet(f)
        if f_frame.shape[0] > 0:
            f_frame.loc[:, 'chromosome'] = f.stem.replace("chromosome-", "")
            frames.append(f_frame)
    intron_locations = pd.concat(frames).reset_index(drop=True)
    return intron_locations
