# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm-mito-scanner',
                'doc_host': 'https://DataAndDeadlifts.github.io',
                'git_url': 'https://github.com/DataAndDeadlifts/llm-mito-scanner',
                'lib_path': 'llm_mito_scanner'},
  'syms': { 'llm_mito_scanner.data.download': { 'llm_mito_scanner.data.download.download_data': ( '00 data.download.html#download_data',
                                                                                                  'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.extract_accession_sequence_records': ( '00 '
                                                                                                                       'data.download.html#extract_accession_sequence_records',
                                                                                                                       'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.get_chromosome_sequence_record': ( '00 '
                                                                                                                   'data.download.html#get_chromosome_sequence_record',
                                                                                                                   'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.get_genomic_genbank_path': ( '00 '
                                                                                                             'data.download.html#get_genomic_genbank_path',
                                                                                                             'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.get_latest_assembly_path': ( '00 '
                                                                                                             'data.download.html#get_latest_assembly_path',
                                                                                                             'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.load_config': ( '00 data.download.html#load_config',
                                                                                                'llm_mito_scanner/data/download.py')},
            'llm_mito_scanner.data.transcription': { 'llm_mito_scanner.data.transcription.extract_sequence_with_positions': ( '01 '
                                                                                                                              'data.transcription.html#extract_sequence_with_positions',
                                                                                                                              'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.filter_chromosome_features_by_type': ( '01 '
                                                                                                                                 'data.transcription.html#filter_chromosome_features_by_type',
                                                                                                                                 'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.format_gene_insert_values': ( '01 '
                                                                                                                        'data.transcription.html#format_gene_insert_values',
                                                                                                                        'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_chromosome_gene_info': ( '01 '
                                                                                                                       'data.transcription.html#get_chromosome_gene_info',
                                                                                                                       'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_dbxref_xref': ( '01 '
                                                                                                                      'data.transcription.html#get_feature_dbxref_xref',
                                                                                                                      'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_dbxrefs': ( '01 '
                                                                                                                  'data.transcription.html#get_feature_dbxrefs',
                                                                                                                  'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_geneid': ( '01 '
                                                                                                                 'data.transcription.html#get_feature_geneid',
                                                                                                                 'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_qualifiers': ( '01 '
                                                                                                                     'data.transcription.html#get_feature_qualifiers',
                                                                                                                     'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_transcript_id': ( '01 '
                                                                                                                        'data.transcription.html#get_feature_transcript_id',
                                                                                                                        'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_gene_and_mrna_relationships': ( '01 '
                                                                                                                              'data.transcription.html#get_gene_and_mrna_relationships',
                                                                                                                              'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_gene_seq_record': ( '01 '
                                                                                                                  'data.transcription.html#get_gene_seq_record',
                                                                                                                  'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_genes': ( '01 '
                                                                                                        'data.transcription.html#get_genes',
                                                                                                        'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_mrna_bookends': ( '01 '
                                                                                                                'data.transcription.html#get_mrna_bookends',
                                                                                                                'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_mrna_gene_id': ( '01 '
                                                                                                               'data.transcription.html#get_mrna_gene_id',
                                                                                                               'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_mrna_intron_positions': ( '01 '
                                                                                                                        'data.transcription.html#get_mrna_intron_positions',
                                                                                                                        'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.make_intron_position_dataframe': ( '01 '
                                                                                                                             'data.transcription.html#make_intron_position_dataframe',
                                                                                                                             'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.normalize_mrna_positions': ( '01 '
                                                                                                                       'data.transcription.html#normalize_mrna_positions',
                                                                                                                       'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.write_genes': ( '01 '
                                                                                                          'data.transcription.html#write_genes',
                                                                                                          'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.write_mrna_gene_relationships': ( '01 '
                                                                                                                            'data.transcription.html#write_mrna_gene_relationships',
                                                                                                                            'llm_mito_scanner/data/transcription.py')},
            'llm_mito_scanner.training.transcription.generation': { 'llm_mito_scanner.training.transcription.generation.format_mrna_insert_values': ( '03 '
                                                                                                                                                      'training.transcription.generation.html#format_mrna_insert_values',
                                                                                                                                                      'llm_mito_scanner/training/transcription/generation.py'),
                                                                    'llm_mito_scanner.training.transcription.generation.get_gene': ( '03 '
                                                                                                                                     'training.transcription.generation.html#get_gene',
                                                                                                                                     'llm_mito_scanner/training/transcription/generation.py'),
                                                                    'llm_mito_scanner.training.transcription.generation.get_mrna': ( '03 '
                                                                                                                                     'training.transcription.generation.html#get_mrna',
                                                                                                                                     'llm_mito_scanner/training/transcription/generation.py'),
                                                                    'llm_mito_scanner.training.transcription.generation.get_mrna_from_gene': ( '03 '
                                                                                                                                               'training.transcription.generation.html#get_mrna_from_gene',
                                                                                                                                               'llm_mito_scanner/training/transcription/generation.py'),
                                                                    'llm_mito_scanner.training.transcription.generation.get_mrna_intron_locations': ( '03 '
                                                                                                                                                      'training.transcription.generation.html#get_mrna_intron_locations',
                                                                                                                                                      'llm_mito_scanner/training/transcription/generation.py'),
                                                                    'llm_mito_scanner.training.transcription.generation.get_mrna_locations': ( '03 '
                                                                                                                                               'training.transcription.generation.html#get_mrna_locations',
                                                                                                                                               'llm_mito_scanner/training/transcription/generation.py'),
                                                                    'llm_mito_scanner.training.transcription.generation.write_mrna': ( '03 '
                                                                                                                                       'training.transcription.generation.html#write_mrna',
                                                                                                                                       'llm_mito_scanner/training/transcription/generation.py')},
            'llm_mito_scanner.training.transcription.index': { 'llm_mito_scanner.training.transcription.index.get_intron_locations': ( '02 '
                                                                                                                                       'training.transcription.index.html#get_intron_locations',
                                                                                                                                       'llm_mito_scanner/training/transcription/index.py')},
            'llm_mito_scanner.training.transcription.sampling': { 'llm_mito_scanner.training.transcription.sampling.create_genes_index': ( '04 '
                                                                                                                                           'training.transcription.sampling.html#create_genes_index',
                                                                                                                                           'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.create_mrna_index': ( '04 '
                                                                                                                                          'training.transcription.sampling.html#create_mrna_index',
                                                                                                                                          'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.get_gene_transcript_samples': ( '04 '
                                                                                                                                                    'training.transcription.sampling.html#get_gene_transcript_samples',
                                                                                                                                                    'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.get_gene_transcript_samples_wrapper': ( '04 '
                                                                                                                                                            'training.transcription.sampling.html#get_gene_transcript_samples_wrapper',
                                                                                                                                                            'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.get_multiple_training_sequences_wrapper': ( '04 '
                                                                                                                                                                'training.transcription.sampling.html#get_multiple_training_sequences_wrapper',
                                                                                                                                                                'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.get_training_sequences_with_idx': ( '04 '
                                                                                                                                                        'training.transcription.sampling.html#get_training_sequences_with_idx',
                                                                                                                                                        'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.sample_intron_edges': ( '04 '
                                                                                                                                            'training.transcription.sampling.html#sample_intron_edges',
                                                                                                                                            'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.sample_introns': ( '04 '
                                                                                                                                       'training.transcription.sampling.html#sample_introns',
                                                                                                                                       'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.sample_mrna': ( '04 '
                                                                                                                                    'training.transcription.sampling.html#sample_mrna',
                                                                                                                                    'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.sample_mrna_edges': ( '04 '
                                                                                                                                          'training.transcription.sampling.html#sample_mrna_edges',
                                                                                                                                          'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.sample_sequences_idx': ( '04 '
                                                                                                                                             'training.transcription.sampling.html#sample_sequences_idx',
                                                                                                                                             'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.tokenize_gene': ( '04 '
                                                                                                                                      'training.transcription.sampling.html#tokenize_gene',
                                                                                                                                      'llm_mito_scanner/training/transcription/sampling.py'),
                                                                  'llm_mito_scanner.training.transcription.sampling.tokenize_mrna': ( '04 '
                                                                                                                                      'training.transcription.sampling.html#tokenize_mrna',
                                                                                                                                      'llm_mito_scanner/training/transcription/sampling.py')},
            'llm_mito_scanner.training.transcription.train': { 'llm_mito_scanner.training.transcription.train.PositionalEncoding': ( '05 '
                                                                                                                                     'training.transcription.train.html#positionalencoding',
                                                                                                                                     'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.PositionalEncoding.__init__': ( '05 '
                                                                                                                                              'training.transcription.train.html#positionalencoding.__init__',
                                                                                                                                              'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.PositionalEncoding.forward': ( '05 '
                                                                                                                                             'training.transcription.train.html#positionalencoding.forward',
                                                                                                                                             'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.Seq2SeqTransformer': ( '05 '
                                                                                                                                     'training.transcription.train.html#seq2seqtransformer',
                                                                                                                                     'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.Seq2SeqTransformer.__init__': ( '05 '
                                                                                                                                              'training.transcription.train.html#seq2seqtransformer.__init__',
                                                                                                                                              'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.Seq2SeqTransformer.decode': ( '05 '
                                                                                                                                            'training.transcription.train.html#seq2seqtransformer.decode',
                                                                                                                                            'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.Seq2SeqTransformer.encode': ( '05 '
                                                                                                                                            'training.transcription.train.html#seq2seqtransformer.encode',
                                                                                                                                            'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.Seq2SeqTransformer.forward': ( '05 '
                                                                                                                                             'training.transcription.train.html#seq2seqtransformer.forward',
                                                                                                                                             'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.TokenEmbedding': ( '05 '
                                                                                                                                 'training.transcription.train.html#tokenembedding',
                                                                                                                                 'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.TokenEmbedding.__init__': ( '05 '
                                                                                                                                          'training.transcription.train.html#tokenembedding.__init__',
                                                                                                                                          'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.TokenEmbedding.forward': ( '05 '
                                                                                                                                         'training.transcription.train.html#tokenembedding.forward',
                                                                                                                                         'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.TranscriptionDataset': ( '05 '
                                                                                                                                       'training.transcription.train.html#transcriptiondataset',
                                                                                                                                       'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.TranscriptionDataset.__getitem__': ( '05 '
                                                                                                                                                   'training.transcription.train.html#transcriptiondataset.__getitem__',
                                                                                                                                                   'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.TranscriptionDataset.__init__': ( '05 '
                                                                                                                                                'training.transcription.train.html#transcriptiondataset.__init__',
                                                                                                                                                'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.TranscriptionDataset.__len__': ( '05 '
                                                                                                                                               'training.transcription.train.html#transcriptiondataset.__len__',
                                                                                                                                               'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.TranscriptionDataset.save_index': ( '05 '
                                                                                                                                                  'training.transcription.train.html#transcriptiondataset.save_index',
                                                                                                                                                  'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.build_vocab': ( '05 '
                                                                                                                              'training.transcription.train.html#build_vocab',
                                                                                                                              'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.collate_fn': ( '05 '
                                                                                                                             'training.transcription.train.html#collate_fn',
                                                                                                                             'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.count_tokens_in_sequence_file': ( '05 '
                                                                                                                                                'training.transcription.train.html#count_tokens_in_sequence_file',
                                                                                                                                                'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.create_mask': ( '05 '
                                                                                                                              'training.transcription.train.html#create_mask',
                                                                                                                              'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.evaluate': ( '05 '
                                                                                                                           'training.transcription.train.html#evaluate',
                                                                                                                           'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.generate_square_subsequent_mask': ( '05 '
                                                                                                                                                  'training.transcription.train.html#generate_square_subsequent_mask',
                                                                                                                                                  'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.get_vocab': ( '05 '
                                                                                                                            'training.transcription.train.html#get_vocab',
                                                                                                                            'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.greedy_decode': ( '05 '
                                                                                                                                'training.transcription.train.html#greedy_decode',
                                                                                                                                'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.list_string_to_list': ( '05 '
                                                                                                                                      'training.transcription.train.html#list_string_to_list',
                                                                                                                                      'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.sequential_transforms': ( '05 '
                                                                                                                                        'training.transcription.train.html#sequential_transforms',
                                                                                                                                        'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.set_text_transform': ( '05 '
                                                                                                                                     'training.transcription.train.html#set_text_transform',
                                                                                                                                     'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.set_vocab_idx': ( '05 '
                                                                                                                                'training.transcription.train.html#set_vocab_idx',
                                                                                                                                'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.tensor_transform': ( '05 '
                                                                                                                                   'training.transcription.train.html#tensor_transform',
                                                                                                                                   'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.train_epoch': ( '05 '
                                                                                                                              'training.transcription.train.html#train_epoch',
                                                                                                                              'llm_mito_scanner/training/transcription/train.py'),
                                                               'llm_mito_scanner.training.transcription.train.translate': ( '05 '
                                                                                                                            'training.transcription.train.html#translate',
                                                                                                                            'llm_mito_scanner/training/transcription/train.py')}}}
