# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm-mito-scanner',
                'doc_host': 'https://DataAndDeadlifts.github.io',
                'git_url': 'https://github.com/DataAndDeadlifts/llm-mito-scanner',
                'lib_path': 'llm_mito_scanner'},
  'syms': { 'llm_mito_scanner.data.download': { 'llm_mito_scanner.data.download.download_data': ( '00 data.download.html#download_data',
                                                                                                  'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.extract_accession_sequence_records': ( '00 '
                                                                                                                       'data.download.html#extract_accession_sequence_records',
                                                                                                                       'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.get_chromosome_sequence_record': ( '00 '
                                                                                                                   'data.download.html#get_chromosome_sequence_record',
                                                                                                                   'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.get_genomic_genbank_path': ( '00 '
                                                                                                             'data.download.html#get_genomic_genbank_path',
                                                                                                             'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.get_latest_assembly_path': ( '00 '
                                                                                                             'data.download.html#get_latest_assembly_path',
                                                                                                             'llm_mito_scanner/data/download.py'),
                                                'llm_mito_scanner.data.download.load_config': ( '00 data.download.html#load_config',
                                                                                                'llm_mito_scanner/data/download.py')},
            'llm_mito_scanner.data.transcription': { 'llm_mito_scanner.data.transcription.filter_chromosome_features_by_type': ( '01 '
                                                                                                                                 'data.transcription.html#filter_chromosome_features_by_type',
                                                                                                                                 'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_chromosome_gene_info': ( '01 '
                                                                                                                       'data.transcription.html#get_chromosome_gene_info',
                                                                                                                       'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_dbxref_xref': ( '01 '
                                                                                                                      'data.transcription.html#get_feature_dbxref_xref',
                                                                                                                      'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_dbxrefs': ( '01 '
                                                                                                                  'data.transcription.html#get_feature_dbxrefs',
                                                                                                                  'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_geneid': ( '01 '
                                                                                                                 'data.transcription.html#get_feature_geneid',
                                                                                                                 'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_qualifiers': ( '01 '
                                                                                                                     'data.transcription.html#get_feature_qualifiers',
                                                                                                                     'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_feature_transcript_id': ( '01 '
                                                                                                                        'data.transcription.html#get_feature_transcript_id',
                                                                                                                        'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_gene_and_mrna_relationships': ( '01 '
                                                                                                                              'data.transcription.html#get_gene_and_mrna_relationships',
                                                                                                                              'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_gene_seq_record': ( '01 '
                                                                                                                  'data.transcription.html#get_gene_seq_record',
                                                                                                                  'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_input_sequence': ( '01 '
                                                                                                                 'data.transcription.html#get_input_sequence',
                                                                                                                 'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_mrna_gene_id': ( '01 '
                                                                                                               'data.transcription.html#get_mrna_gene_id',
                                                                                                               'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_mrna_intron_positions': ( '01 '
                                                                                                                        'data.transcription.html#get_mrna_intron_positions',
                                                                                                                        'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.get_target_sequence': ( '01 '
                                                                                                                  'data.transcription.html#get_target_sequence',
                                                                                                                  'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.normalize_mrna_positions': ( '01 '
                                                                                                                       'data.transcription.html#normalize_mrna_positions',
                                                                                                                       'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.write_chromosome_gene_info': ( '01 '
                                                                                                                         'data.transcription.html#write_chromosome_gene_info',
                                                                                                                         'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.write_input_and_target_sequences': ( '01 '
                                                                                                                               'data.transcription.html#write_input_and_target_sequences',
                                                                                                                               'llm_mito_scanner/data/transcription.py'),
                                                     'llm_mito_scanner.data.transcription.write_mrna_gene_relationships': ( '01 '
                                                                                                                            'data.transcription.html#write_mrna_gene_relationships',
                                                                                                                            'llm_mito_scanner/data/transcription.py')},
            'llm_mito_scanner.training.transcription.index': { 'llm_mito_scanner.training.transcription.index.TranscriptionDataset': ( '02 '
                                                                                                                                       'training.transcription.index.html#transcriptiondataset',
                                                                                                                                       'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.TranscriptionDataset.__getitem__': ( '02 '
                                                                                                                                                   'training.transcription.index.html#transcriptiondataset.__getitem__',
                                                                                                                                                   'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.TranscriptionDataset.__init__': ( '02 '
                                                                                                                                                'training.transcription.index.html#transcriptiondataset.__init__',
                                                                                                                                                'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.TranscriptionDataset.__len__': ( '02 '
                                                                                                                                               'training.transcription.index.html#transcriptiondataset.__len__',
                                                                                                                                               'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.batchify': ( '02 '
                                                                                                                           'training.transcription.index.html#batchify',
                                                                                                                           'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.batchify_sequence': ( '02 '
                                                                                                                                    'training.transcription.index.html#batchify_sequence',
                                                                                                                                    'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.build_vocab': ( '02 '
                                                                                                                              'training.transcription.index.html#build_vocab',
                                                                                                                              'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.count_transcription_tokens': ( '02 '
                                                                                                                                             'training.transcription.index.html#count_transcription_tokens',
                                                                                                                                             'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.get_batch': ( '02 '
                                                                                                                            'training.transcription.index.html#get_batch',
                                                                                                                            'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.get_sequence': ( '02 '
                                                                                                                               'training.transcription.index.html#get_sequence',
                                                                                                                               'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.get_training_index': ( '02 '
                                                                                                                                     'training.transcription.index.html#get_training_index',
                                                                                                                                     'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.get_vocab': ( '02 '
                                                                                                                            'training.transcription.index.html#get_vocab',
                                                                                                                            'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.make_train_test_split': ( '02 '
                                                                                                                                        'training.transcription.index.html#make_train_test_split',
                                                                                                                                        'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.make_training_index': ( '02 '
                                                                                                                                      'training.transcription.index.html#make_training_index',
                                                                                                                                      'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.process_training_sequence': ( '02 '
                                                                                                                                            'training.transcription.index.html#process_training_sequence',
                                                                                                                                            'llm_mito_scanner/training/transcription/index.py'),
                                                               'llm_mito_scanner.training.transcription.index.tokenize': ( '02 '
                                                                                                                           'training.transcription.index.html#tokenize',
                                                                                                                           'llm_mito_scanner/training/transcription/index.py')}}}
