# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_validate-sequences.ipynb.

# %% auto 0
__all__ = ['load_gene_and_protein', 'validate_gene_and_protein']

# %% ../../nbs/04_validate-sequences.ipynb 3
import pandas as pd
from pathlib import Path
from tqdm.auto import tqdm
from Bio import SeqIO

# %% ../../nbs/04_validate-sequences.ipynb 6
def load_gene_and_protein(
    gene_id: str, 
    protein_id: str, 
    gene_path: Path, 
    protein_path: Path
) -> (SeqIO.SeqRecord, SeqIO.SeqRecord):
    gene = next(SeqIO.parse(gene_path / f"{gene_id}.fasta", "fasta"))
    protein = next(SeqIO.parse(protein_path / f"{protein_id}.fasta", "fasta"))
    return gene, protein

# %% ../../nbs/04_validate-sequences.ipynb 9
def validate_gene_and_protein(gene: SeqIO.SeqRecord, protein: SeqIO.SeqRecord) -> bool:
    """
    Returns true if a dna sequence maps directly to a protein sequence.
    """
    translated_gene = gene.translate(cds=True)
    return translated_gene.seq == protein.seq
